version: "3"
services:
  httpd:
    image: ${DOCKER_MT_IMAGE:-movabletype/dev:perl-5.20}
    restart: always
    entrypoint: "/usr/local/bin/docker-entrypoint.sh"
    volumes:
      - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt"
      - "${MT_CONFIG_CGI:-../mt-config.cgi-original}:${MT_CONFIG_CGI_DEST_PATH:-/var/www/cgi-bin/mt/mt-config.cgi}"
      - "${BASE_SITE_PATH:-site}:/var/www/html"
      - "${MT_HOME_PATH:-../../movabletype}/mt-static:/var/www/html/mt-static"
      - "support:/var/www/cgi-bin/mt/mt-static/support"
      - "support:/var/www/html/mt-static/support"
    ports:
      - "${HTTPD_EXPOSE_PORT:-80}:80"
    command: "/usr/sbin/httpd -D FOREGROUND"
  psgi:
    image: busybox

volumes:
  site:
    driver: local
  support:
    driver: local
