version: "3"
services:
  mt:
    image: ${DOCKER_MT_IMAGE:-movabletype/dev:perl-5.20}
    restart: always
    entrypoint: "/usr/local/bin/mt-docker-entrypoint.sh"
    volumes:
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt"
      - "${MT_CONFIG_CGI:-../mt-config.cgi-original}:${MT_CONFIG_CGI_DEST_PATH:-/var/www/cgi-bin/mt/mt-config.cgi}"
      - "${BASE_SITE_PATH:-site}:/var/www/html"
      - "support:/var/www/cgi-bin/mt/mt-static/support"
      # override entrypoint
      - "./mt-docker-entrypoint.sh:/usr/local/bin/mt-docker-entrypoint.sh"

  httpd:
    image: ${DOCKER_HTTPD_IMAGE:-movabletype/dev:php-7.2}
    restart: always
    volumes:
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt"
      - "${MT_CONFIG_CGI:-../mt-config.cgi-original}:${MT_CONFIG_CGI_DEST_PATH:-/var/www/cgi-bin/mt/mt-config.cgi}"
      - "${BASE_SITE_PATH:-site}:/var/www/html"
      - "support:/var/www/cgi-bin/mt/mt-static/support"
      # proxy setting
      - "./cgi-bin-mt.htaccess:/var/www/html/cgi-bin/mt/.htaccess"
    ports:
      - "${HTTPD_EXPOSE_PORT:-80}:80"

volumes:
  site:
    driver: local
  support:
    driver: local
  mt-dev-mt-home-tmp:
    external: true
