version: "3"
services:
  db:
    image: ${DOCKER_MYSQL_IMAGE:-mariadb:10.0}
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "${DOCKER_MYSQL_VOLUME:-mariadb10}:/var/lib/mysql"
volumes:
  mariadb10:
    driver: local
  mysql8:
    driver: local
